server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_learn_01?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root1234
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml



