server:
  port: 8081

spring:
  application:
    name: mall_learn_14
  datasource:
    url: jdbc:mysql://localhost:3306/mall_learn?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root1234
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    database: 0
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 3000ms

redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:mbg_mapper/*.xml
    - classpath*:deecyn/**/mapper/*.xml

jwt:
  tokenHeader: Authorization # JWT 存储的请求头
  secret: mySecret # JWT 加密、解密使用的密钥
  expiration: 8640_0000 # token 的过期时间，（毫秒数：1000 * 60 * 60 * 24）
  tokenHead: Bearer # JWT 负载中拿到开头




